module.exports = {
  supportedAlgorithms: [
    'bastion',
    'bitcore',
    'blake',
    'blake2s',
    'blakecoin',
    'bmw',
    'c11',
    'cryptolight',
    'cryptonight',
    'decred',
    'deep',
    'dmd-gr',
    'equihash',
    'flax',
    'fresh',
    'fugue256',
    'groestl',
    'heavy',
    'hmq1725',
    'jha',
    'keccak',
    'lbry',
    'luffa',
    'lyra2',
    'lyra2v2',
    'lyra2z',
    'mjollnir',
    'myr-gr',
    'neoscrypt',
    'nist5',
    'penta',
    'qubit',
    's3',
    'sha256d',
    'sha256t',
    'sia',
    'sib',
    'skein',
    'skein2',
    'timetravel',
    'vanilla',
    'veltor',
    'whirlcoin',
    'whirlpool',
    'wildkeccak',
    'x11',
    'x11evo',
    'x13',
    'x14',
    'x15',
    'x17',
    'zr5',
  ],
  timedBenchmark: true,
  mineCmdLine: (algorithm, cudaGpuId, stratumUri, username) => [
    '-a', algorithm,
    '-d', cudaGpuId,
    '-o', `stratum+tcp://${stratumUri}`,
    '-u', username,
    '-p', 'x',
    '-b', 0
  ],
  benchmarkCmdLine: (algorithm, cudaGpuId) => [
    '-a', algorithm,
    '-d', cudaGpuId,
    '-b', 0,
    '--benchmark'
  ],
  extractHashrate: stdoutLine => {
    let match = /(?:GPU #\d+: .+,|Total:) ([\d.]+) ([kMGTP]?H|Sol)\/s/.exec(stdoutLine);
    return match ? [parseFloat(match[1]), match[2]] : null;
  },
  killProcess: ps => {
    ps.kill('SIGINT');
  }
};